### PR TITLE
Add option for yuzu directory

### PR DESCRIPTION
**Pull request by maltejur**
Screenshot 2021-07-27 133408

### CODE REVIEW

**Comment by EL86** [comment]
Question, when I extract the zip and look in the folder, I can't find the exe file, where is it?

**Comment by amakvana** [comment]
> Question, when I extract the zip and look in the folder, I can't find the exe file, where is it?

Ensure your antivirus hasn't tried to remove the .exe from the .zip. I can confirm that both the .exe and .dll are present in the .zip archive

**Comment by EL86** [comment]
> > Question, when I extract the zip and look in the folder, I can't find the exe file, where is it?
> 
> Ensure your antivirus hasn't tried to remove the .exe from the .zip. I can confirm that both the .exe and .dll are present in the .zip archive

I'm pretty sure that my antivirus hasn't done anything, here is the folder image after extracting.
image

**Comment by amakvana** [comment]
> > > Question, when I extract the zip and look in the folder, I can't find the exe file, where is it?
> > 
> > 
> > Ensure your antivirus hasn't tried to remove the .exe from the .zip. I can confirm that both the .exe and .dll are present in the .zip archive
> 
> I'm pretty sure that my antivirus hasn't done anything, here is the folder image after extracting.
> image

Download it from the URL below:
https://github.com/amakvana/YuzuModDownloader/releases/latest

**Comment by maltejur** [comment]
> @maltejur
> The directories are automatically detected within the ModDownloader.cs class, therefore having a dialog to browse to it is not required

I haven't removed the automatic detection, that still works. I have just added the option to change the automatically detected directory, for the case that the user has the yuzu folder in another location.

For example I want to use the program on linux with [wine](https://www.winehq.org/), where the standard yuzu directory is located at `Z:\home\maltejur\.local\share\yuzu`.

**Comment by amakvana** [comment]
> > I'll look to add in some custom folder options soon
> 
> Is there still something you would change in the pr?

Possibly, but semantics and maybe having a checkbox option or something. Once it hits the weekend, I'll have more chance to think about it as I'm juggling two jobs at the moment 🤣

**Comment by maltejur** [comment]
Ah yes sure no pressure :D

And a checkbox shouldn't be necessary since by default the detected path is in the field and the user doesn't have to touch it at all.

**Comment by maltejur** [comment]
Ahh the damn bot, I'll open another PR

**Pull request closed without merging**
